# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
AllCops:
  TargetRubyVersion: 2.6.2

Bundler/OrderedGems:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
Style/NumericLiterals:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/TrivialAccessors:
  AllowDSLWriters: true
Style/EmptyCaseCondition:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Enabled: true
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
